### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by allanscullion**
Hi,

First up, thanks for the great work. I have made some changes so that it will work with my blog setup and publish method 

I have created this pull request for your consideration.

A number of improvements:
- Git push and site publish is now optional
  - See conf.Global.always_publish
- Handles ARTICLE_URL values when constructing the post URL (including {date:} tags)
- Searches both publishconf.py and pelicanconf.py for Pelican values (publishconf.py takes precedence)
- Allows for a git repo that only contains the Pelican content folder
- Tweets are triggered by adding "Triggers: tweet" to the post metadata (Triggers is a comma delimited list)
  - See conf.Global.tweet_trigger
- Added exception handling to the Bitly and Twitter API calls
- Minor fix to conf_sample.py: renamed Twitter.access_token to Twitter.access_token_key

FWIW, you should checkout codeship.io :) I use it to auto publish my blog whenever I push to my git repo. For this kind of basic use tt is free.

Take care
Allan

### CODE REVIEW

**Comment by quack1** [comment]
Hi !

Thank you very much for your interest on the project and your great PR ! I'm gonna review it tonight or tomorrow and test it and merge it if everything's OK.

I'll keep you updated :)

**Comment by allanscullion** [comment]
Cool. Thanks.

I am considering creating a new project called something like pelican_triggers. This will include the post tweet functionality and others - mainly Facebook, but could be extended to other social media platforms.

I would like to re-use your lib pelican.py file in the project. Are you ok with this providing I give you the proper credit?

Cheers
Allan

**Comment by quack1** [comment]
Yes, of course you can use it :) Thank you for using my work !

BTW, the code is licenced under a BSD licence so you can use it and share it :)

**Comment by quack1** [comment]
BTW, if you want to avoid some extra development you could just fork this project or add functionality to it. Providing extra social media sharing capabilities could be nice too :)

**Comment by quack1** [comment]
Hi @allanscullion ,

I just merge your commits to a new branch and do some updates to fix the "broken" things I found.
Can you try pulling my commits from https://github.com/quack1/pelican_auto_tweet/tree/allanscullion-master and tell me if everything is OK ?
If you're ok with my commits and it works with your Pelican install I'll merge your branch and my fixes :)

**Comment by allanscullion** [comment]
Hi @quack1 

On sight, it looks good to me. The only thing that might be worth updating is the sample config file to include the new Conf values:)

I confess I am still learning Python. Your project has become a little learning project for me. I am going to attempt a new repo with heavily refactored code. Given the nature of the changes, I feel the project needs renaming, so a new repo sort of makes sense.

As soon as I have something working, I'll let you know and we can decide if/how to merge. Perhaps we can collaborate when I have a working version? Doing this in my limited spare time, so could take a while :)

Cheers
Allan

**Comment by quack1** [comment]
Hi ! Yes, I might have forget some new values in the configuration sample. I will check this out and merge the code into the master trunk :)

I think too that adding some new sharing system to the code would need many refactoring... If you want to avoid creating a new repo and thus "lose" some possible updates to libpelican or other pieces of code, you can create a new branch on this repository and work on it. This way it could also be more easy for me to help you and contribute to the code if everything is centralize :p 

Anyway, thank you very much for your help on this project and your interest on it ! :)

**Pull request merged**
